---
title: "EDCS access and merging of TXT files"
author: "Petra Hermankova"
date: "27/11/2020"
output:
  html_document:
    theme: united
    toc: yes
    toc_float: true
    number_sections: true
    toc_depth: 2
    df_print: paged
---

```{r setup, include=FALSE, echo=FALSE}
require("knitr")
opts_knit$set(root.dir = "/home/petra/Github/ClaussSlaby_ETL/")

library(tidyverse)
library(data.table)
library(sdam)
library(jsonlite)
```


```{r}
# listing all tsv files
temp = list.files(path= "/home/petra/Github/ClaussSlaby_ETL/data/2020_12_allProvinces/", pattern = "*.tsv")
```

# Loading data from multiple TSV files
```{r}

# loading multiples files
setwd("/home/petra/Github/ClaussSlaby_ETL/data/2020_12_allProvinces/")
EDCS <- temp %>% map_df(~read_tsv(., col_types = cols(.default = "c")))
setwd("/home/petra/Github/ClaussSlaby_ETL/")
```

```{r}
head(EDCS)
```

```{r}
names(EDCS)
```

# Saving to Sciencedata

```{r, echo=FALSE}
mycred_secret<- readLines("~/mysecret.txt")
```

```{r}
EDCS_json <- jsonlite::toJSON(EDCS, auto_unbox=TRUE)
write(EDCS_json, file="EDCS_merged_2020-12-09.json")
request("EDCS_merged_2020-12-09.json", path="/sharingout/648597@au.dk/SDAM_root/SDAM_data/EDCS/",
        method="PUT", cred=c(mycred_secret[1], mycred_secret[2]))
```

```{r, echo=FALSE}
remove(mycred_secret)
```



