---
title: "Text mining of lemmatized corpus"
author: "Petra Hermankova"
date: "26/01/2021"
output:
  html_document:
    theme: united
    toc: yes
    toc_float: true
    number_sections: true
    toc_depth: 2
    df_print: paged
---

```{r setup, include=FALSE, echo=FALSE}
require("knitr")
opts_knit$set(root.dir = "/home/petra/Github/EDCS_ETL/")

library(tidyverse)
library(jsonlite)
library(data.table)
library(sdam)
```

## Loading data
Load the dataset, if you have Sciencedata.dk credentials

```{r, echo=FALSE}
mycred_secret<- readLines("~/mysecret.txt")
```

```{r, loading data}
resp = request("EDCS_text_lemmatized_proiel_2021-01-22.json", path="/sharingin/648597@au.dk/SDAM_root/SDAM_data/EDCS/public", method="GET", cred=mycred_secret)
```

```{r, echo=FALSE}
remove(mycred_secret)
```

OR of you don't have Sciencedata credentials:
```{r, loading data public, eval=FALSE}
#The folder still needs to made public by owner (Vojtech Kase)
# resp = request("EDCS_text_lemmatized_proiel_2021-01-22.json", path="/shared/1f5f56d09903fe259c0906add8b3a55e", method="GET")
```

Make a list and tibble from the downloaded dataset
```{r}
list_json <- jsonlite::fromJSON(resp)
EDCS_proiel = as_tibble(list_json)
```
